@startuml business
left to right direction

actor User as guest

package Groups{
  actor "Admin" as admin
  actor "Office" as off
  actor "IT group" as gs
}

package Service {
  usecase "Read only" as ro
  usecase "Edit" as e
  usecase "Change roles/images" as cr
  usecase "Add infos" as ai
}

guest --> ro
admin --> e
admin --> cr
admin --> ai
off --> cr
off --> ai
gs --> ai
@enduml
