@startuml oauth
Frontend -> Keycloak: Requests the login page
activate Keycloak
Keycloak -> Frontend: Redirects to his own login page
Keycloak -> Keycloak: Waits for the user to login/register
Keycloak -> Frontend: Sends the Authentication and bearer
deactivate Keycloak
Frontend -> Backend: Requests a service with bearer token in the header
activate Backend
Backend -> Keycloak: Requests the public key
Keycloak -> Backend: Gives the key
Backend -> Backend: Unapcks the JWT
Backend -> Backend: Checks user role and fetch the api
Backend -[#red]-> Frontend: Gives error if not authenticate to the api
Backend -> Frontend: Gives the resources if authenticated
deactivate Backend
@enduml