# Fase di build
FROM node:16 AS build

# Imposta la cartella di lavoro
WORKDIR /app

# Copia i file di configurazione delle dipendenze
COPY frontend/vue-frontend/package*.json ./

# Installa le dipendenze
RUN npm install

# Copia il resto del codice sorgente
COPY frontend/vue-frontend/src ./src
COPY frontend/vue-frontend/public ./public

# Costruisci l'applicazione
RUN npm run build

# Fase di produzione
FROM nginx:alpine

# Copia i file di build nella directory di Nginx
COPY --from=build /app/dist /usr/share/nginx/html

# Espone la porta 80
EXPOSE 80

# Comando per avviare Nginx
CMD ["nginx", "-g", "daemon off;"]
