FROM node:16 AS build

WORKDIR /app

# Copy the package.json and package-lock.json (if available)
COPY front-end/package*.json ./

# Install dependencies
RUN npm install

# Copy the entire front-end folder (including src, public, and index.html)
COPY front-end/ ./

# Run the build command
RUN npm run build

# Stage 2: Serve with NGINX
FROM nginx:alpine

# Copy the built files from the previous build stage into NGINX's serving directory
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 8081

CMD ["nginx", "-g", "daemon off;"]
